### ISSUE TITLE
Error deploying when environment is defined at function level

### ISSUE THREAD

**Issue by mzuniga84** [rurri/serverless-resources-env#4]
I'm getting an error when trying to deploy a function with environment defined.

This is my function definition:

functions:
  processor:
    handler: functions/processor/handler.handler
    events:
      - schedule: 
          rate: rate(5 minutes)
          enabled: true
    environment:
      MAX_NUMBER_OF_MESSAGES: 10
    custom:
      env-resources:
        - processingQueue

The error I'm getting is: **Expected params.Environment.Variables['MAX_NUMBER_OF_MESSAGES']
     to be a string**

**Comment by rurri** [comment]
HI @mzuniga84 This can be fixed by making MAX_NUMBER_OF_MESSAGES: "10". Since env variables will end up as strings anyways.

In code you will need to parse this into an int.

`const maxMessages = parseInt(process.env. MAX_NUMBER_OF_MESSAGES)`
